import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import React from "react";
import QueryProvider from "@/provider/query-provider";

// const font = Inter({ subsets: ["latin"] });
const font = Merriweather({
  weight: ["400", "300", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Qviple",
  description: "Generated by create next app",
};
// export async function generateMetadata() {
//   const id = useStore((state: State) => state.id);
//   const { data: websiteInfoByInstitute } = useWebsiteInfoByInstitute(id);
//   console.info("websiteInfoByInstitute ->", websiteInfoByInstitute);
//   return {
//     title: `My Blog`,
//     description: "post.excerpt",
//   };
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
