import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import React from "react";
import QueryProvider from "@/provider/query-provider";
import LandingWrapper from "@/components/landing-wrapper";

// const font = Inter({ subsets: ["latin"] });
const font = Merriweather({
  weight: ["400", "300", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
